sudo: required
dist: focal

script:
  - kustomize_release_url=$(curl -vsIo /dev/null https://github.com/kubernetes-sigs/kustomize/releases/latest 2>&1 | grep 'location:' | cut -d ' ' -f 3)
  - kustomize_version=$(basename "$kustomize_release_url")
  - echo $kustomize_version
